[package]
name = "sha2-js"
version = "0.1.0"
edition = "2018"

[lib]
name = "thread_count"
crate-type = ["cdylib"]

[build-dependencies]
neon-build = "0.3.3"

[dependencies]
sha2 = "0.9.8"
neon = "0.3"
